/**
 * This file is part of the securitypro package.
 *
 * @author Mathias Reker
 * @copyright Mathias Reker
 * @license Commercial Software License
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

!function(t){"use strict";var a=function(a){this.element=t(a)};a.prototype={constructor:a,show:function(){var a,e,i,s=this.element,n=s.closest("ul:not(.dropdown-menu)"),o=s.attr("data-target");o||(o=(o=s.attr("href"))&&o.replace(/.*(?=#[^\s]*$)/,"")),s.parent("li").hasClass("active")||(a=n.find(".active:last a")[0],i=t.Event("show",{relatedTarget:a}),s.trigger(i),i.isDefaultPrevented()||(e=t(o),this.activate(s.parent("li"),n),this.activate(e,e.parent(),function(){s.trigger({type:"shown",relatedTarget:a})})))},activate:function(a,e,i){var s=e.find("> .active"),n=i&&t.support.transition&&s.hasClass("fade");function o(){s.removeClass("active").find("> .dropdown-menu > .active").removeClass("active"),a.addClass("active"),n?(a[0].offsetWidth,a.addClass("in")):a.removeClass("fade"),a.parent(".dropdown-menu")&&a.closest("li.dropdown").addClass("active"),i&&i()}n?s.one(t.support.transition.end,o):o(),s.removeClass("in"),scroll(0,0)}};var e=t.fn.tab;t.fn.tab=function(e){return this.each(function(){var i=t(this),s=i.data("tab");s||i.data("tab",s=new a(this)),"string"==typeof e&&s[e]()})},t.fn.tab.Constructor=a,t.fn.tab.noConflict=function(){return t.fn.tab=e,this},t(document).on("click.tab.data-api",'[data-toggle="tab"], [data-toggle="pill"]',function(a){a.preventDefault(),t(this).tab("show")})}(window.jQuery),function(t){t.createTabs=function(){t("#content").find('form [id^="fieldset"]').length&&(blockTab='<div class="col-lg-2"><div id="module-tabs" class="list-group">',t.each(t("#content").find('form [id^="fieldset"]'),function(){heading=t(this).find(".panel-heading, legend"),blockTab+='<a href="#'+t(this).attr("id")+'" class="list-group-item" id="'+t(this).attr("id")+'_securitypro" data-toggle="tab">'+heading.html()+"</a>",t(this).addClass("tab-pane")}),blockTab+="</div></div>",t("#content").find("form").wrap("<div class='row'></div>").before(blockTab).addClass("col-lg-10 tab-content"),t("#content").find("form > br").remove(),t("#content").find("#module-tabs a:first").tab("show").addClass("active"),t("#content").find(".list-group-item").on("click",function(){var a=t(this).parent().closest(".list-group").children(".active");a.hasClass("active")&&a.removeClass("active"),t(this).addClass("active")}))}}(jQuery),$(document).ready(function(){$.createTabs(),$('a[data-toggle="tab"]').on("shown",function(t){localStorage.setItem("lastTab",$(t.target).attr("id"))});var t=localStorage.getItem("lastTab");t&&($("#"+t).tab("show"),$("#fieldset_0_securitypro").removeClass("active"),$("#"+t).addClass("active"))}),$(document).ready(function(){$("#module-tabs").after("<div id='module-tabs' class='list-group'><a class='list-group-item' style='text-align: center;'><i class='icon-info'></i> "+securitypro.text9+" "+securitypro.moduleVersion+" | <i class='icon-info'></i> "+securitypro.cmsName+" "+securitypro.cmsVersion+"</a></div>")});
