<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFyfbudh\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFyfbudh/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFyfbudh.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFyfbudh\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFyfbudh\appProdProjectContainer([
    'container.build_hash' => 'Fyfbudh',
    'container.build_id' => 'a55b2eea',
    'container.build_time' => 1711297302,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFyfbudh');
