<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDmaaskt\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDmaaskt/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerDmaaskt.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerDmaaskt\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerDmaaskt\appProdProjectContainer([
    'container.build_hash' => 'Dmaaskt',
    'container.build_id' => 'bc29e1a2',
    'container.build_time' => 1711146560,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDmaaskt');
