<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMxxl2rm\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMxxl2rm/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMxxl2rm.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMxxl2rm\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMxxl2rm\appProdProjectContainer([
    'container.build_hash' => 'Mxxl2rm',
    'container.build_id' => '341abc13',
    'container.build_time' => 1701871884,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMxxl2rm');
